apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: my-web-app-container
        image: omercelikel23/flask-docker-app:latest  # Docker Hub'dan çekilecek imaj
        ports:
        - containerPort: 80  # Konteynerın dinleyeceği port