name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: polar-standard-412817

    - name: Connect to GKE
      run: |
        gcloud container clusters get-credentials autopilot-cluster-1 --region europe-west1 --project polar-standard-412817

    - name: Deploy to GKE
      run: kubectl apply -f deployment.yaml
