name: DevSecOps Workflow

on:
  push:
    branches:
      - main

jobs:
  code-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.1'
    - name: Code Scan with Snyk
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: test
        args: --severity-threshold=critical

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: code-scan
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: omercelikel23/flask-docker-app:latest

  image-scan:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
    - name: Scan the Docker image with Snyk
      uses: snyk/actions/docker@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: omercelikel23/flask-docker-app:latest
        command: test
        args: --severity-threshold=critical
  
  deploy-to-eks:
    runs-on: ubuntu-latest
    needs: image-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: eu-north-1
      
      - name: Deploy to EKS
        run: |
          # EKS Cluster'ina bağlanin ve dağitim komutlarinizi calistirin
          aws eks --region eu-north-1 update-kubeconfig --name cluster
          # Kubernetes manifest dasyasini kullanarak uygulamayi dagitin
          kubectl apply -f deployment.yaml