name: DevSecOps Workflow

on:
  push:
    branches:
      - main

jobs:
  code-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.1'
    - name: Code Scan with Snyk
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: test
        args: --severity-threshold=critical

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: code-scan
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: omercelikel23/flask-docker-app:latest

  image-scan:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
    - name: Scan the Docker image with Snyk
      uses: snyk/actions/docker@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: omercelikel23/flask-docker-app:latest
        command: test
        args: --severity-threshold=critical

  deploy:
    runs-on: ubuntu-latest
    needs: [image-scan]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}
        project_id: polar-standard-412817

    - name: Connect to GKE
      run: |
        gcloud container clusters get-credentials autopilot-cluster-1 --region europe-southwest1 --project polar-standard-412817
      

    - name: Deploy to GKE
      run: kubectl apply -f deployment.yaml